---
title: "Publications"
---

## 专著
- 陈国权、毛益民等：《权力法治与廉政治理》，中国社会科学出版社，2018年7月。

- 陈国权等：《权力制约监督论》，浙江大学出版社，2013年出版（本人为第二作者），本书获第七届教育部高等学校科学研究优秀成果奖（人文社会科学）三等奖


## 论文

### 英文
- Mao, Y. (2018). Decentralization, national context and environmental policy performance: a fuzzy set qualitative comparative analysis. Environmental Science and Pollution Research, Online first. [Link](https://link.springer.com/article/10.1007%2Fs11356-018-2846-9)

- Mao, Y. (2018). Does democratic transition reduce carbon intensity? Evidence from Indonesia using the synthetic control method. Environmental Science and Pollution Research, 25(20), 19908–19917. [link](https://link.springer.com/article/10.1007%2Fs11356-018-2165-1)


### 中文
- 毛益民、陈国权：《民主反腐的情境适配：一项跨国比较分析》，《经济社会体制比较》，2018年第2期。[链接](http://www.cnki.com.cn/Article/CJFDTotal-JJSH201802010.htm)

- 毛益民：《腐败涉入的自我合理化：一种认知心理学分析》，《廉政文化研究》，2017年第4期。

- 毛益民：《地方项目化治理的权力异化及其衍生效应》，《广东行政学院学报》，2016年第5期。

- 陈国权、毛益民：《第三区域政企统合治理与集权化现象研究》，《政治学研究》，2015年第2期（人大复印资料《中国政治》2015年第7期转载）[链接](http://mall.cnki.net/magazine/Article/POLI201502005.htm)


- 毛益民：《制度逻辑冲突：场域约束与管理实践》，《广东社会科学》，2014年第6期。

- 毛益民：《论监督控权失灵的内在成因与制度根源》，《理论与改革》，2014年第2期。

- 毛益民：《治理网络、问责困境与政府元治理》，《广东行政学院学报》，2013年第5期。

- 陈国权、毛益民：《腐败裂变式扩散：一种社会交换分析》，《浙江大学学报（人文社科版）》，2013年第2期（《高等学校文科学术文摘》2013年第3期转载）。

- 陈国权、毛益民：《道德制约权力：现实与可能》，《学术月刊》，2012 年第2期（人大复印资料《伦理学》2012年第5期全文转载）。

- 毛益民：《马恩论权力制约监督的几个问题》，《北京日报》，2011 年8月29日专稿（《学习时报》2011年10月24日转载）


## 会议论文与报告
- Mao Yimin.Study on the Influencing Factors of Local Government Innovation Diffusion, 2011 International Conference on Public Administration (ICPA 7th),indexed by CPCI-SSH。


## 编著章节
- 《创新型政府：杭州的探索与实践》（伍彬、陈国权主编，浙江大学出版社，2014年7月）第一、二章


## 博士论文
- 毛益民：《集体腐败的形成机理：基于结构、行为与认知的分析》，浙江大学2015年。获浙江省、浙江大学2016年度优秀博士论文提名奖。

